import mongoose from 'mongoose';

// Software model
const softwareSchema = new mongoose.Schema({
  software_name: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: false,
  },
  // The _id field is automatically generated by Mongoose, so no need to specify it explicitly
});

const Software = mongoose.model('Software', softwareSchema);
export default Software;
